### ISSUE TITLE
Intel 2018 compile issue with libfabric v1.6

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#4063]
I got a customer-reported bug today:

> We are working on implementing OpenMPI 3.1 on our new cluster network implementation (migrating to a new VLAN, all hosts with usNIC enabled), but it seems that libfabric-1.6 is required (compile complained that libfabric-1.4 was dependent upon libnl v1 and v3). So I am working on a libfabric-1.6 compilation using Intel 2018 compilers on RHEL6.9, but running into an error:

```
In file included from ./include/ofi.h(50),
                 from ./include/ofi_util.h(55),
                 from src/fabric.c(44):
./include/ofi_atom.h(66): error: identifier "atomic_int_least32_t" is undefined
  	typedef atomic_int_least32_t	ofi_atomic_int32_t;
  	        ^
In file included from ./include/ofi.h(50),
                 from ./include/ofi_util.h(55),
                 from src/fabric.c(44):
./include/ofi_atom.h(67): error: identifier "atomic_int_least64_t" is undefined
  	typedef atomic_int_least64_t	ofi_atomic_int64_t;
```

> If I also add GCC-6.2 compilers to my environment, the configure works, but the make gives repeated warnings over and over, before eventually completing:

```
In file included from ./include/ofi.h(50),
                 from ./include/ofi_util.h(55),
                 from src/fabric.c(44):
./include/ofi_atom.h(66): error: identifier "atomic_int_least32_t" is undefined
  	typedef atomic_int_least32_t	ofi_atomic_int32_t;
  	        ^
... 
 In file included from ./include/ofi.h(50),
                 from ./include/ofi_util.h(55),
                 from prov/tcp/src/tcpx_comm.c(36):
./include/ofi_atom.h(263): warning #2330: argument of type "ofi_atomic_int64_t={atomic_int_least64_t={_Atomic(long)}} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OFI_ATOMIC_DEFINE(64)
  ^
```

> I don't think loading the GCC is the way to go, and I don't recall needing to do that before. Any research on atomic_int_least64 is referencing me to libstdc++, which I have installed. If you have any suggestions, I would greatly appreciate the assist.

I'm waiting for my Intel 2018 licenses to come through, so I can't test this out myself at the moment.  

@shefty is there anyone there at Intel who can provide an assist here?

**Comment by shefty** [comment]
Can you try 1.6.1rc1?

See

https://github.com/ofiwg/libfabric/commit/818243e89a6a5c2e4a3aa775d9897513fba2cbc9

- Sean

**Comment by jsquyres** [comment]
I've asked the customer to test.

**Comment by jsquyres** [comment]
I got my own Intel 2018 license and tried to compile the HEAD of the libfabric v1.6.x branch and got oodles of warnings.  [See this gist](https://gist.github.com/jsquyres/1cff01c34cfd7c418b405b48fbfcf25b).

The main warnings are like this:

```
  CC       src/src_libfabric_la-fabric.lo
In file included from ./include/ofi.h(50),
                 from ./include/ofi_util.h(55),
                 from src/fabric.c(44):
./include/ofi_atom.h(267): warning #2330: argument of type "ofi_atomic_int32_t={atomic_int_least32_t={_Atomic(int)}} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OFI_ATOMIC_DEFINE(32)
  ^
```

**Comment by jsquyres** [comment]
(BTW, this happens on master, too)

It's probably important to note that I'm on RHEL 6.5 (the customer cited RHEL 6.9).

**Comment by jsquyres** [comment]
I should also point out that all these warnings occur on both `ofi_atom.h` lines 267 and 268, i.e.:

```c
OFI_ATOMIC_DEFINE(32)
OFI_ATOMIC_DEFINE(64)
```

These are gigantic macros for atomic things.  Can someone smarter than me about the libfabric atomics have a look at this?

**Comment by jsquyres** [comment]
Looks like this was fixed long ago.
