### ISSUE TITLE
libfabric main compilation breaks for GCC 4.8.5

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#8574]
**Describe the bug**
On CentOS and Red Hat 7 OS, which has default GCC version as 4.8.5, the libfabric main branch cannot be compiled.

**To Reproduce**
On CentOS and Red Hat 7 OS

```
./autogen.sh
./configure --prefix=$PWD/install
make -j
```

**Output**
A snippet of the error log is as follows, , a full log will be attached

```
 CC       util/info.o
  CC       util/strerror.o
  CC       util/pingpong.o
In file included from ./include/ofi_shm.h:48:0,
                 from prov/util/src/util_shm.c:44:
./include/ofi_shm.h: In function 'smr_cmd_queue_next':
./include/ofi_shm.h:290:44: warning: implicit declaration of function 'atomic_load_explicit' [-Wimplicit-function-declaration]
 OFI_DECLARE_ATOMIC_Q(struct smr_cmd_entry, smr_cmd_queue);
                                            ^
./include/ofi_atomic_queue.h:143:9: note: in definition of macro 'OFI_DECLARE_ATOMIC_Q'
  struct name ## _entry *ce;    \
         ^
./include/ofi_atomic_queue.h:145:44: error: request for member 'val' in something not a structure or union
  *pos = atomic_load_explicit(&aq->write_pos.val,  \
                                            ^
./include/ofi_shm.h:290:1: note: in expansion of macro 'OFI_DECLARE_ATOMIC_Q'
 OFI_DECLARE_ATOMIC_Q(struct smr_cmd_entry, smr_cmd_queue);
 ^
./include/ofi_atomic_queue.h:146:9: error: 'memory_order_relaxed' undeclared (first use in this function)
         memory_order_relaxed); \
         ^
./include/ofi_shm.h:290:1: note: in expansion of macro 'OFI_DECLARE_ATOMIC_Q'
 OFI_DECLARE_ATOMIC_Q(struct smr_cmd_entry, smr_cmd_queue);
 ^
./include/ofi_atomic_queue.h:146:9: note: each undeclared identifier is reported only once for each function it appears in
```

**Environment:**
Red Hat/CentOS 7, GCC 4.8.5

**Additional context**
This issue should be introduced by https://github.com/ofiwg/libfabric/pull/8221. We understand this GCC version is low, but our customers will be impacted as these two OSes have not reached their EOL.

**Comment by shijin-aws** [comment]
[compile_centos7.txt](https://github.com/ofiwg/libfabric/files/10844185/compile_centos7.txt)

**Comment by shijin-aws** [comment]
@amirshehataornl

**Comment by amirshehataornl** [comment]
looking into it. I'm able to reproduce and trying to find the best way to handle this.

**Comment by shijin-aws** [comment]
@amirshehataornl  Thanks!

**Comment by amirshehataornl** [comment]
https://github.com/ofiwg/libfabric/pull/8576
can you give this a whirl. I ran it on my centos7 and it passed the shm tests.

**Comment by shijin-aws** [comment]
I tested https://github.com/ofiwg/libfabric/pull/8576 and it fixes the compilation issue on my centos7

**Comment by amirshehataornl** [comment]
now it fails windows compilation... have to look into that.

**Comment by amirshehataornl** [comment]
question, should centos7 be added to the AWS build cycle, if it's one of the platforms supported, probably good idea to build it as well.

**Comment by shijin-aws** [comment]
We can add it in AWS CI. I am not sure if @shefty is ok with adding it to build checks in the github actions.

**Comment by shefty** [comment]
I'm okay expanding the build checks in github, if this is a supported option.

**Comment by amirshehataornl** [comment]
I'm a bit stuck with the windows side of things in https://github.com/ofiwg/libfabric/pull/8576, any suggestions? I have a comment on the PR.

**Comment by shefty** [comment]
Fixed by #8576.
