### PR TITLE
2.0 deprecations

### PR DESCRIPTION
**Pull request by j-xiong**
This is the first part of reworked #10009. It contains all the API deprecations. Major changes from the original PR:
* APIs are marked deprecated instead of removed. 
* Compiler directives are added to generate warnings when the deprecated APIs are used.
* Provider support for these deprecated APIs is mostly retained (especially w.r.t. MR modes, wait set, and poll set).
* Providers used Internal version of the deprecated APIs to maintain compatibility while avoiding compiler warnings.

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
@shijin-aws Could you check the AWS CI error?

**Comment by shijin-aws** [comment]
Ompi 4.1.x failed to compile with this PR. @wenduwan The log is pretty long and I haven't seen how it could be caused by this PR

```
mtl_ofi.h: In function ‘ompi_mtl_ofi_context_progress’:
mtl_ofi_request.h:19:5: error: implicit declaration of function ‘container_of’ [-Werror=implicit-function-declaration]
   19 |     container_of((_ptr_ctx), struct ompi_mtl_ofi_request_t, ctx)
      |     ^~~~~~~~~~~~
mtl_ofi.h:121:31: note: in expansion of macro ‘TO_OFI_REQ’
  121 |                     ofi_req = TO_OFI_REQ(ompi_mtl_ofi_wc[i].op_context);
      |                               ^~~~~~~~~~
mtl_ofi_request.h:19:30: error: expected expression before ‘struct’
   19 |     container_of((_ptr_ctx), struct ompi_mtl_ofi_request_t, ctx)
      |                              ^~~~~~
mtl_ofi.h:121:31: note: in expansion of macro ‘TO_OFI_REQ’
  121 |                     ofi_req = TO_OFI_REQ(ompi_mtl_ofi_wc[i].op_context);
      |                               ^~~~~~~~~~
mtl_ofi_request.h:19:30: error: expected expression before ‘struct’
   19 |     container_of((_ptr_ctx), struct ompi_mtl_ofi_request_t, ctx)
      |                              ^~~~~~
mtl_ofi.h:167:23: note: in expansion of macro ‘TO_OFI_REQ’
  167 |             ofi_req = TO_OFI_REQ(error.op_context);
```

**Comment by wenduwan** [comment]
This looks odd. But one oddity in open mpi is `mtl_ofi.h` and `mtl_ofi_request.h` have circular dependency. Not sure how it was working before though.

**Comment by wenduwan** [comment]
@hppritcha Do you have any thoughts?

For libfabric 2.0 do we need to make configury changes in ompi?

**Comment by j-xiong** [comment]
This first commit in the PR removed `container_of` from the public headers: 
https://github.com/ofiwg/libfabric/pull/10250/commits/6ac82423dd98c622f9210fb77738a5b5816e47bc

That's probably the reason of the failure.

**Comment by wenduwan** [comment]
In this case I think open mpi should be more defensive, and define its own container_of - @hppritcha what do you think?

**Comment by wenduwan** [comment]
@j-xiong While I don't think open mpi is doing the right thing, I also wonder if there is a strong reason to move the container_of macro in libfabric?

As a result of this change, existing open mpi tarballs will not build with libfabric 2.0. There might be other problems as well but we can go from here.

**Comment by shijin-aws** [comment]
ompi cannot rely on `container_of` from libfabric headers, it's something broken on the ompi side

**Comment by j-xiong** [comment]
`container_of` is not supposed be defined in libfabric public headers. Libfabric core and providers use it so we still have it defined internally. Applications should define their own.

**Comment by wenduwan** [comment]
I agree with the long-term plan to have applications define container_of individually. But I would like to explore it is ok to keep it in libfabric header for now so open mpi(and maybe other affected packages) can take actions separately. In other words, does container_of have to be relocated as part of libfabric 2.0?

**Review by shefty — APPROVED** [review]
I didn't notice any issues.  Not sure if the Pragma works for all builds (windows, OS X, etc.)

**Comment by wenduwan** [comment]
I see. So moving this macro likely requires major version bump. This makes sense.

Thanks for the suggestion. I need to poke the open mpi community on the mitigation for users who want to build old open mpi with libfabric 2.0.

**Comment by j-xiong** [comment]
The pragma works with macos. Result from macos build check:
```
common/check_hmem.c:47:34: warning: 'FI_MR_BASIC' is deprecated [-W#pragma-messages]
        hints->domain_attr->mr_mode = ~(FI_MR_BASIC | FI_MR_SCALABLE);
                                        ^
/Users/runner/work/libfabric/libfabric/fabtests/../install/include/rdma/fabric.h:232:22: note: expanded from macro 'FI_MR_BASIC'
#define FI_MR_BASIC             _Pragma("GCC warning \"'FI_MR_BASIC' is deprecated\"")          (1 << 0)
                                ^
<scratch space>:43:6: note: expanded from here
 GCC warning "'FI_MR_BASIC' is deprecated"
     ^
```

On windows it is not recognized and produces a warning will still serves the purpose of attracting the attention:
```
common\shared.c(281): warning C4068: unknown pragma 'GCC' [C:\projects\libfabric\fabtests\fabtests.vcxproj]
```

**Comment by j-xiong** [comment]
I am going to ignore the AWC CI failure for now. Please let me know if there are any other concerns about that.

**Comment by shijin-aws** [comment]
@j-xiong can you hold it for 1 day, we need to fix our CI otherwise all the future main branch PR will fail after this one is merged.

**Comment by j-xiong** [comment]
@shijin-aws Sure. Please let me know when you think it is ready.

File: man/fi_endpoint.3.md [hunk 1]
```diff
@@ -1048,11 +1048,6 @@ transfer operation in order to guarantee that ordering is met.
   update operations.  If not atomic updates may be
   transmitted out of order from their submission.
 
-*FI_ORDER_NONE*
```
Comment (aingerson) [inline man/fi_endpoint.3.md:1079]: Do you want to remove or add a deprecated note like the others?

File: man/fi_av.3.md [hunk 2]
```diff
@@ -138,19 +139,18 @@ endpoint communicates using a proprietary network protocol.  The
...
-headers.
+returned through an AV insertion call.
 
 The process of mapping an address is fabric and provider specific,
 but may involve lengthy address resolution and fabric management
-protocols.  AV operations are synchronous by default, but may be set
-to operate asynchronously by specifying the FI_EVENT flag to
-`fi_av_open`.  When requesting asynchronous operation, the application
-must first bind an event queue to the AV before inserting addresses.  See
+protocols.  AV operations are synchronous by default. See
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply man/fi_av.3.md:146]: The alternative is in the deprecated section, but I think I can make it clearer.

File: man/fi_av.3.md [hunk 3]
```diff
@@ -197,6 +199,10 @@ struct fi_av_attr {
   of the first address inserted into an FI_AV_TABLE will be 0, and
   successive insertions will be given sequential indices.  Sequential
   indices will be assigned across insertion calls on the same AV.
+  Because the fi_addr_t values returned from an insertion call are
+  deterministic, applications may not need to provide the fi_addr_t
+  output parameters to insertion calls.  The exception is when
+  authentication keys are required for communication.
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply man/fi_av.3.md:205]: The removed part just enumerates a few possible cases which table index as one of them. There are removed because we don't really need those details here, especially since we are deprecating the av map semantics.

The upper 32-bit usage is in a later patch, we don't need to count for that now.

File: fabtests/unit/getinfo_test.c [hunk 4]
```diff
@@ -181,8 +181,7 @@ static int validate_tx_ordering_bits(char *node, char *service, uint64_t flags,
 		struct fi_info *hints, struct fi_info **info)
 {
 	return validate_bit_combos(node, service, flags, hints, info,
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply fabtests/unit/getinfo_test.c:183]: hmm, we should use 0x1FF here.

File: man/fi_endpoint.3.md (hunk 1 above)
Comment (j-xiong) [reply man/fi_endpoint.3.md:1079]: This one was missed in the transition. Need to add a deprecated note.

File: prov/util/src/util_av.c [hunk 5]
```diff
@@ -258,18 +258,6 @@ void *ofi_av_addr_context(struct util_av *av, fi_addr_t fi_addr)
 
 int ofi_verify_av_insert(struct util_av *av, uint64_t flags, void *context)
 {
-	if (av->flags & FI_EVENT) {
-		if (!av->eq) {
-			FI_WARN(av->prov, FI_LOG_AV, "no EQ bound to AV\n");
-			return -FI_ENOEQ;
-		}
-
-		if (flags & FI_SYNC_ERR) {
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply prov/util/src/util_av.c:267]: This flag allows details of errors being reported for synchronous av insertion. It doesn't require av-eq binding, but requires the context parameter pointing to array for storing error codes.

**Comment by wenduwan** [comment]
bot:aws:retest

**Comment by wenduwan** [comment]
Fixed open mpi main branch by moving around container_of definition. Now rerun AWS CI to find other problems.

**Comment by shijin-aws** [comment]
https://github.com/open-mpi/ompi/pull/12724 has been merged to ompi main to fix the illegal container_of import

The current plan is to backport this fix to 4.1.x and 5.0.x branch by today, since we are always building the head of ompi branches in AWS CI, this should be ok

File: man/fi_av.3.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (shijin-aws) [reply man/fi_av.3.md:206]: I thought another exception is `FI_AV_TABLE_USER_ID`? In that case `fi_addr_t` is also an input.

[the remark this answers is not in the document]
Comment (j-xiong) [reply man/fi_av.3.md:206]: I am changing this to: ` The exception is when the fi_addr_t parameters are also used as input for supplying    authentication keys or user defined IDs`

File: prov/efa/src/efa_prov_info.c [hunk 6]
```diff
@@ -73,7 +73,7 @@ const struct fi_domain_attr efa_domain_attr = {
 	.control_progress	= FI_PROGRESS_AUTO,
 	.data_progress		= FI_PROGRESS_AUTO,
 	.resource_mgmt		= FI_RM_DISABLED,
-	.mr_mode		= OFI_MR_BASIC_MAP | FI_MR_LOCAL | FI_MR_BASIC,
+	.mr_mode		= OFI_MR_BASIC_MAP | FI_MR_LOCAL | OFI_MR_BASIC,
```
Comment (shijin-aws) [inline prov/efa/src/efa_prov_info.c:76]: I believe efa code has more occurrence for `FI_LOCAL_MR` to handle old API, but it's ok to leave as is for this PR

File: man/fi_av.3.md [hunk 7]
```diff
@@ -685,7 +676,7 @@ buffer associated with a failed or aborted insertion will be set to
 FI_ADDR_NOTAVAIL.
 
 All other calls return FI_SUCCESS on success, or a negative value corresponding
-to fabric errno on error. Fabric errno values are defined in `rdma/fi_errno.h`.
+to fabric errno on error.  Fabric errno values are defined in `rdma/fi_errno.h`.
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply man/fi_av.3.md:679]: As a convention, double spaces have been used in the man pages between full sentences. Doesn't seem to affect the output though.

File: include/rdma/fi_domain.h [hunk 8]
```diff
@@ -327,7 +327,7 @@ struct fi_ops_mr {
 };
 
 /* Domain bind flags */
-#define FI_REG_MR		(1ULL << 59)
+#define FI_REG_MR		(1ULL << 59)  /* deprecated */
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply include/rdma/fi_domain.h:330]: yes.

File: prov/efa/src/efa_prov_info.c (hunk 6 above)
Comment (j-xiong) [reply prov/efa/src/efa_prov_info.c:76]: There is only one occurrence in efa unit test, which I think should leave it as it is (tests are only supposed to see public headers).

Comment (shijin-aws) [reply prov/efa/src/efa_prov_info.c:76]: yep yep

**Comment by wenduwan** [comment]
@shijin-aws Can you restart AWS CI?

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
@shijin-aws @wenduwan What is the current CI error?

**Comment by wenduwan** [comment]
```
nit/getinfo_test.c:565:13: warning: 'FI_MR_SCALABLE' is deprecated
   info->domain_attr->mr_mode != FI_MR_SCALABLE) ?
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unit/eq_test.c: In function ‘main’:
unit/eq_test.c:614:3: error: ‘FI_BUFFERED_RECV’ undeclared (first use in this function); did you mean ‘FI_DIRECTED_RECV’?
   FI_BUFFERED_RECV;
   ^~~~~~~~~~~~~~~~
   FI_DIRECTED_RECV
unit/eq_test.c:614:3: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by wenduwan** [comment]
Plus warnings...
```
functional/rdm_atomic.c: In function ‘handle_atomic_base_op’:
functional/rdm_atomic.c:180:31: warning: comparison between ‘enum fi_datatype’ and ‘enum <anonymous>’ [-Wenum-compare]
   for (datatype = 0; datatype < FI_DATATYPE_LAST; datatype++) { \
                               ^
functional/rdm_atomic.c:279:1: note: in expansion of macro ‘create_atomic_op_handler’
 create_atomic_op_handler(base)
 ^~~~~~~~~~~~~~~~~~~~~~~~
functional/rdm_atomic.c: In function ‘handle_atomic_fetch_op’:
functional/rdm_atomic.c:180:31: warning: comparison between ‘enum fi_datatype’ and ‘enum <anonymous>’ [-Wenum-compare]
   for (datatype = 0; datatype < FI_DATATYPE_LAST; datatype++) { \
                               ^
functional/rdm_atomic.c:280:1: note: in expansion of macro ‘create_atomic_op_handler’
 create_atomic_op_handler(fetch)
 ^~~~~~~~~~~~~~~~~~~~~~~~
functional/rdm_atomic.c: In function ‘handle_atomic_compare_op’:
functional/rdm_atomic.c:180:31: warning: comparison between ‘enum fi_datatype’ and ‘enum <anonymous>’ [-Wenum-compare]
   for (datatype = 0; datatype < FI_DATATYPE_LAST; datatype++) { \
                               ^
functional/rdm_atomic.c:281:1: note: in expansion of macro ‘create_atomic_op_handler’
 create_atomic_op_handler(compare)
 ^~~~~~~~~~~~~~~~~~~~~~~~
functional/rdm_atomic.c: In function ‘run_ops’:
functional/rdm_atomic.c:338:33: warning: comparison between ‘enum fi_op’ and ‘enum <anonymous>’ [-Wenum-compare]
  for (op_type = FI_MIN; op_type < FI_ATOMIC_OP_LAST; op_type++) {
                                 ^
functional/rdm_atomic.c: In function ‘get_mr_key’:
functional/rdm_atomic.c:372:13: warning: 'FI_MR_BASIC' is deprecated
  return ((fi->domain_attr->mr_mode == FI_MR_BASIC) ||
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
functional/rdm_atomic.c: In function ‘main’:
functional/rdm_atomic.c:506:17: warning: comparison between ‘enum fi_op’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (op_type == FI_ATOMIC_OP_LAST) {
                 ^~
functional/rdm_atomic.c:518:18: warning: comparison between ‘enum fi_datatype’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (datatype == FI_DATATYPE_LAST) {
                  ^~
```

**Comment by wenduwan** [comment]
```
server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.33.58 'timeout 1000 /bin/bash --login -c '"'"'FI_LOG_LEVEL=warn ASAN_OPTIONS=detect_leaks=0:protect_shadow_gap=0 /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr10250-debug-mempoison-asan/install/fabtests/bin/fi_efa_exhaust_mr_reg_rdm_pingpong -I 5 -v -S all -p efa -E'"'"''

Client error: Server has terminated

server_stdout:

bind: Address already in use


server returncode: 1

____________________ test_rma_bw_1G[delivery_complete-read] ____________________

efa/test_rma_bw.py:62: in test_rma_bw_1G

    efa_run_client_server_test(cmdline_args, command, 2,

efa/efa_common.py:26: in efa_run_client_server_test

    test.run()

../../../../../../../../../env/lib64/python3.8/site-packages/retrying.py:56: in wrapped_f

    return Retrying(*dargs, **dkw).call(f, *args, **kw)

../../../../../../../../../env/lib64/python3.8/site-packages/retrying.py:257: in call

    return attempt.get(self._wrap_exception)

../../../../../../../../../env/lib64/python3.8/site-packages/retrying.py:301: in get

    six.reraise(self.value[0], self.value[1], self.value[2])

../../../../../../../../../env/lib64/python3.8/site-packages/six.py:719: in reraise

    raise value

../../../../../../../../../env/lib64/python3.8/site-packages/retrying.py:251: in call

    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

common.py:573: in run

    check_returncode_list([server_process.returncode, client_returncode],

common.py:223: in check_returncode_list

    pytest.fail(reason)

E   Failed: returncode 1

```

Now I'm seeing a bunch of fabtests failures

**Comment by wenduwan** [comment]
Looks like our port randomization logic was lost somewhere 🤔

**Review by belynam — APPROVED** [review]

**Comment by wenduwan** [comment]
@j-xiong We have a couple CI changes coming up but it will take some time to deploy. Let me rerun the test locally.

**Comment by wenduwan** [comment]
@shijin-aws @j-xiong Could you restart AWS CI? Our fixes have been deployed.

**Comment by j-xiong** [comment]
bot:aws:restart

**Comment by wenduwan** [comment]
bot:aws:restart > bot:aws:retest

**Comment by j-xiong** [comment]
bot:aws:retest
