### PR TITLE
prov/verbs: Fix compiling issue with GCC < 4.6

### LINKED ISSUE #3677: verbs provider fails to compile with gcc 4.4.7 (RHEL 6 default compiler)
This is master head as of 2018-01-11:

```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make
make  all-am
make[1]: Entering directory `/home/jsquyres/git/libfabric'
  CC       prov/verbs/src/src_libfabric_la-fi_verbs.lo
In file included from prov/verbs/src/fi_verbs.c:37:
prov/verbs/src/fi_verbs.h: In function ‘fi_ibv_mem_notifier_set_free_hook’:
prov/verbs/src/fi_verbs.h:537: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:538: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:540: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h: In function ‘fi_ibv_mem_notifier_set_realloc_hook’:
prov/verbs/src/fi_verbs.h:564: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:565: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:567: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h: In function ‘fi_ibv_mem_notifier_get_free_hook’:
prov/verbs/src/fi_verbs.h:591: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:592: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:594: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h: In function ‘fi_ibv_mem_notifier_get_realloc_hook’:
prov/verbs/src/fi_verbs.h:618: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:619: error: #pragma GCC diagnostic not allowed inside functions
prov/verbs/src/fi_verbs.h:621: error: #pragma GCC diagnostic not allowed inside functions
make[1]: *** [prov/verbs/src/src_libfabric_la-fi_verbs.lo] Error 1
make[1]: Leaving directory `/home/jsquyres/git/libfabric'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Fixes #3677 

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by a-ilango** [comment]
I think the gcc diagnostic push/pop are the unsupported pragmas in older GCC versions. So every invocation of that has to be wrapped in version checks.

**Comment by gladkovdmitry17** [comment]
Sorry, I forgot to apply this for all places.
I've update the PR. It should work now.

**Comment by gladkovdmitry17** [comment]
The OSX/Clang and OSX/GCC Travis jobs are hanging.
Merging this PR
