### ISSUE TITLE
master HEAD build broken: logging errors in verbs provider

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#806]
When I try to build the current HEAD (v1.0.0rc2-350-g41e7e2e), I get the following compile errors:

```
  CC       prov/verbs/src/src_libfabric_la-fi_verbs.lo
In file included from ./include/fi.h:46:0,
                 from prov/verbs/src/fi_verbs.c:58:
prov/verbs/src/fi_verbs.c: In function 'fi_ibv_getinfo':
prov/verbs/src/fi_verbs.c:705:11: warning: passing argument 1 of 'fi_log_enabled' makes pointer from integer without a cast
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
           ^
./include/rdma/fi_log.h:74:22: note: in definition of macro 'FI_LOG'
   if (fi_log_enabled(prov, subsystem, level))   \
                      ^
./include/rdma/fi_log.h:66:5: note: expected 'const struct fi_provider *' but argument is of type 'int'
 int fi_log_enabled(const struct fi_provider *prov, enum fi_log_level level,
     ^
./include/rdma/fi_log.h:74:7: error: incompatible type for argument 2 of 'fi_log_enabled'
   if (fi_log_enabled(prov, subsystem, level))   \
       ^
prov/verbs/src/fi_verbs.c:705:4: note: in expansion of macro 'FI_LOG'
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
    ^
./include/rdma/fi_log.h:66:5: note: expected 'enum fi_log_level' but argument is of type 'char *'
 int fi_log_enabled(const struct fi_provider *prov, enum fi_log_level level,
     ^
./include/rdma/fi_log.h:74:7: error: incompatible type for argument 3 of 'fi_log_enabled'
   if (fi_log_enabled(prov, subsystem, level))   \
       ^
prov/verbs/src/fi_verbs.c:705:4: note: in expansion of macro 'FI_LOG'
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
    ^
./include/rdma/fi_log.h:66:5: note: expected 'enum fi_log_subsys' but argument is of type 'char *'
 int fi_log_enabled(const struct fi_provider *prov, enum fi_log_level level,
     ^
./include/rdma/fi_log.h:76:36: error: expected expression before ')' token
     __func__, __LINE__, __VA_ARGS__); \
                                    ^
prov/verbs/src/fi_verbs.c:705:4: note: in expansion of macro 'FI_LOG'
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
    ^
prov/verbs/src/fi_verbs.c:705:11: warning: passing argument 1 of 'fi_log' makes pointer from integer without a cast
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
           ^
./include/rdma/fi_log.h:75:11: note: in definition of macro 'FI_LOG'
    fi_log(prov, level, subsystem,   \
           ^
./include/rdma/fi_log.h:68:6: note: expected 'const struct fi_provider *' but argument is of type 'int'
 void fi_log(const struct fi_provider *prov, enum fi_log_level level,
      ^
./include/rdma/fi_log.h:75:4: error: incompatible type for argument 2 of 'fi_log'
    fi_log(prov, level, subsystem,   \
    ^
prov/verbs/src/fi_verbs.c:705:4: note: in expansion of macro 'FI_LOG'
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
    ^
./include/rdma/fi_log.h:68:6: note: expected 'enum fi_log_level' but argument is of type 'char *'
 void fi_log(const struct fi_provider *prov, enum fi_log_level level,
      ^
./include/rdma/fi_log.h:75:4: error: incompatible type for argument 3 of 'fi_log'
    fi_log(prov, level, subsystem,   \
    ^
prov/verbs/src/fi_verbs.c:705:4: note: in expansion of macro 'FI_LOG'
    FI_LOG(3, "verbs", "Could not create queue pair with requested attributes\n");
    ^
./include/rdma/fi_log.h:68:6: note: expected 'enum fi_log_subsys' but argument is of type 'char *'
 void fi_log(const struct fi_provider *prov, enum fi_log_level level,
      ^
make[1]: *** [prov/verbs/src/src_libfabric_la-fi_verbs.lo] Error 1
make[1]: Leaving directory `/home/jsquyres/git/libfabric2'
make: *** [all] Error 2
```

Disabling the verbs provider seems to avoid the issue.

git bisect says that bc7c70ea2f66e69350a6ffd5b8f054adef28d418 is the problematic commit.
