### ISSUE TITLE
libfabric 1.6.0 fails to compile with icc 13.0.1

### ISSUE THREAD

**Issue by miharulidze** [ofiwg/libfabric#3958]
libfabric 1.5.3 builds fine with icc 13.0.1, but 1.6.0 and current master

**./configure CC=icc  CFLAGS="-g -O0" --enable-g=all --disable-shared && make && make install** 

fails with

```
CC       prov/tcp/src/src_libfabric_la-tcpx_progress.lo
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CC       prov/tcp/src/src_libfabric_la-tcpx_comm.lo
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CCLD     src/libfabric.la
  CC       util/info.o
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CCLD     util/fi_info
src/.libs/libfabric.a(src_libfabric_la-common.o): In function `ofi_cpuid':
/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0/./include/unix/osd.h:260: undefined reference to `__cpuid_count'
/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0/./include/unix/osd.h:260: undefined reference to `__cpuid_count'
make[1]: *** [util/fi_info] Error 1
make[1]: Leaving directory `/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0'
make: *** [all] Error 2
```

**Comment by shefty** [comment]
@vkrishna - Can you look into this?  It looks like these calls are used by the tcp provider.

**Comment by vkrishna** [comment]
Yes. I will check. Thanks

**Comment by vkrishna** [comment]
From the full log, It seems that the issue is not tcp specific but actual problem is that ICC can't find __cpuid_count.

To reproduce this issue, I could not find ICC v13.0.1 (if you have a link to download handy, please point me to it). So I tried to reproduce with v18.0.1. I ran into different issue. I didn't run far enough to reproduce this issue with 18.0.1.

**Comment by miharulidze** [comment]
@vkrishna ICC 13.0.1 has compatibility with GCC 4.3.0. So, you can try to reproduce this issue with GCC. I tried and compilation also fails with same errors.

**Comment by gladkovdmitry17** [comment]
> Can you see if the changes from #3970 work for you?

I checked #3970 with GCC 4.1.0, GCC 4.3.0 and ICC 13. This works fine.

**Comment by miharulidze** [comment]
@shefty, @gladkovdmitry17 I checked #3970 and everything compiles fine both with ICC 13 and GCC 4.3.0. 
Thank you!
