### PR TITLE
build: Check for presence of __cpuid_count

### LINKED ISSUE #3958: libfabric 1.6.0 fails to compile with icc 13.0.1
libfabric 1.5.3 builds fine with icc 13.0.1, but 1.6.0 and current master

**./configure CC=icc  CFLAGS="-g -O0" --enable-g=all --disable-shared && make && make install** 

fails with

```
CC       prov/tcp/src/src_libfabric_la-tcpx_progress.lo
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CC       prov/tcp/src/src_libfabric_la-tcpx_comm.lo
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CCLD     src/libfabric.la
  CC       util/info.o
./include/unix/osd.h(260): warning #266: function "__cpuid_count" declared implicitly
  	__cpuid_count(func, subfunc, cpuinfo[0], cpuinfo[1],
  	^

  CCLD     util/fi_info
src/.libs/libfabric.a(src_libfabric_la-common.o): In function `ofi_cpuid':
/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0/./include/unix/osd.h:260: undefined reference to `__cpuid_count'
/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0/./include/unix/osd.h:260: undefined reference to `__cpuid_count'
make[1]: *** [util/fi_info] Error 1
make[1]: Leaving directory `/mnt/lustre/home/miharulidze/libfabric_clean/libfabric-1.6.0'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by shefty**
Older versions of icc and gcc do not support this intrinsic.  Sigh

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

Fixes #3958

### CODE REVIEW

File: configure.ac [hunk 1]
```diff
@@ -226,6 +226,21 @@ AC_TRY_LINK([#include <stdint.h>],
...
+AC_MSG_CHECKING(compiler support for cpuid)
+AC_TRY_LINK([
+     #include <stddef.h>
+     #include <cpuid.h>],
+    [
+     int a, b, c, d;
+     __cpuid_count(0, 0, a, b, c, d);
+    ],
+    [
+	AC_MSG_RESULT(yes)
```
Comment (gladkovdmitry17) [inline configure.ac]: Wrong indentation?

Comment (shefty) [reply configure.ac]: The indentation is goofy here, but this is the way it is throughout, so I matched it.
